[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install -g pnpm@10.4.1 && $(npm root -g)/../bin/pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["$(npm root -g)/../bin/pnpm build"]

[start]
cmd = "$(npm root -g)/../bin/pnpm start"
