CREATE TABLE `orders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`stripeSessionId` varchar(255),
	`stripePaymentIntentId` varchar(255),
	`status` enum('pending','paid','failed','refunded') NOT NULL DEFAULT 'pending',
	`productName` varchar(255) NOT NULL DEFAULT 'The Briefcase',
	`quantity` int NOT NULL DEFAULT 1,
	`amountCents` int NOT NULL DEFAULT 49900,
	`customerName` varchar(255) NOT NULL,
	`customerEmail` varchar(320) NOT NULL,
	`customerPhone` varchar(64),
	`shippingLine1` varchar(255) NOT NULL,
	`shippingLine2` varchar(255),
	`shippingCity` varchar(128) NOT NULL,
	`shippingState` varchar(128) NOT NULL,
	`shippingPostcode` varchar(20) NOT NULL,
	`shippingCountry` varchar(64) NOT NULL DEFAULT 'Australia',
	`companyName` varchar(255),
	`abn` varchar(32),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `orders_id` PRIMARY KEY(`id`),
	CONSTRAINT `orders_stripeSessionId_unique` UNIQUE(`stripeSessionId`)
);
